### ISSUE TITLE
Username -> Specific Sites

### ISSUE THREAD

**Issue by WebBreacher** [lockfale/OSINT-Framework#30]
So the sites in the Username -> Specific sites section...what are the thoughts about including my https://github.com/WebBreacher/WhatsMyName project in there? The project has over 160 sites with user name enumeration but it is mostly used in Recon-ng, Spiderfoot and using the script in the project.

Do we put every site where you can do user name enumeration or add those to a list/project and note the project in that section?

**Comment by s0lray** [comment]
Automation is better, =)  I think we just add your project and then put something in the description to say that it covers 160+ sites so use that tool, rather than list all of them individually here.  Now I'm going to need to go through all my notes and see if i can add a few for you!

Prepped the add and it will be in tonight's push.
