### ISSUE TITLE
usernamecheck.com sppears on the Google (un)safe browsing database

### ISSUE THREAD

**Issue by guest20** [lockfale/OSINT-Framework#84]
usernamecheck[.]com sppears on the [Google (un)safe browsing database](https://transparencyreport.google.com/safe-browsing/search?url=http:%2F%2Fwww.usernamecheck.com%2F&hl=en-US) and if you  power through and ignore the warning the site is the Apache "it works" page.

I suggest removing their entry.

**Comment by mrpnkt** [comment]
[Looks phishy](https://www.virustotal.com/#/url/8eadb180a32680e1d5925d9ba81a4fb9ae166c6ba6f50fb5f7e3e27321536db0/detection). No updates since at least [01/11/2018](https://web.archive.org/web/20180111021741/http://www.usernamecheck.com/). Remove in [latest pull request](https://github.com/lockfale/OSINT-Framework/pull/85).

**Comment by s0lray** [comment]
Agreed, thanks!
